### PR TITLE
fix several gtags related issues: mission update_gtags.cmd & lack of execution permission

### PR DESCRIPTION
**Pull request by skywind3000**
After the https://github.com/ludovicchabant/vim-gutentags/commit/39dc3ee228bb7cc712d95b0130c233451381e3da commit, gtags generation will require a `update_gtags.sh` or `update_gtags.cmd` script to execute the actual `gtags` command.

But:

1) "update_gtags.sh" on linux platform lacks execution permission
2) "update_gtags.cmd" is missing on Windows platform.

And `gtags_cscope` became unusable on both Linux and Windows due to these two issues.

This PR fixed: 

- https://github.com/ludovicchabant/vim-gutentags/issues/335
- https://github.com/ludovicchabant/vim-gutentags/issues/322
- https://github.com/ludovicchabant/vim-gutentags/issues/332
- https://github.com/ludovicchabant/vim-gutentags/issues/327

### CODE REVIEW

**Comment by skywind3000** [comment]
@ludovicchabant , would you have time to review this ?
`gtags_cscope` is not usable on both Linux and Windows now.

too many related issues.

**Comment by ludovicchabant** [comment]
Thanks for this! Yes, I'm slow with dealing with PRs and issues -- apologies for that.

What are the pros/cons between your version of `update_gtags.cmd` and the one that came from a previous PR? (see https://github.com/ludovicchabant/vim-gutentags/commit/4108ba2a395ef0198c60a8dcdd64751e2a1d5326 )

**Comment by skywind3000** [comment]
1) My version are directly translated from update_gtags.sh, but his version is not.
2) My version supports `FILE_LIST_CMD` environment variable (like `update_gtags.sh`), but his version doesn't
3) The arguments parsing routine of his version is incorrect, he can only accept `--incremental` as the only one possible argument for gtags, but my version accepts arbitrary arguments for gtags.

**Comment by ludovicchabant** [comment]
That's the impression I got from a quick diff, thanks. I updated the file with your version, included the Powershell support fix, but stripped the changeset that fixed the file permissions since this is already in. See 1337b1891b9d98d6f4881982f27aa22b02c80084. Thanks a lot!

**Comment by skywind3000** [comment]
thanks

**Pull request closed without merging**
