### PR TITLE
Another take on fixing tcd brakeage

### PR DESCRIPTION
**Pull request by hkupty**
This uses the fix from PR #97 to cover new dir changes, not covered by previous PR since were added afterwards.

### CODE REVIEW

**Comment by rafi** [comment]
@hkupty Thanks for this follow-up. I don't think you meant to commit `docs/tags`, right?

**Comment by hkupty** [comment]
Yeah, absolutely! I'll remove it from PR as soon as possible.

Cheers

**Comment by hkupty** [comment]
@rafi fixed!

**Comment by ludovicchabant** [comment]
I think we potentially need to keep the support for window/tab-local working dirs in "normal" Vim, no? But check for the patch that introduced the new `getcwd` function and pass a proper window/tab number?

Or is `getcwd` going to _always_ return the correct (potentially local) current dir?

**Comment by ludovicchabant** [comment]
OK, merged!

**Comment by hkupty** [comment]
Thanks!

**Pull request merged**
