### PR TITLE
Ignore SIGPIPE reported by nvim 0.4 on exit

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/ludovicchabant/vim-gutentags/issues/249.

### CODE REVIEW

**Comment by blueyed** [comment]
Note that this is untested - I just happened to have an old checkout of gutentags laying around, and it was reported on IRC.
(I rather update my tags on demand (via `make-tags` wrapper script), and also during switching of branches in Git.  That's much better performance wise.

**Comment by odrzutowiec** [comment]
Thanks! This solved the problem form me, I had constant 141 error when closing nvim with gutentags

**Comment by ludovicchabant** [comment]
Ah thanks! I was just replying to another pull request about this problem and I had a very similar solution (see https://gist.github.com/ludovicchabant/b3e0477d38d7817fac64d08944f03a35 ). It looks like `v:exiting` doesn't exist in vanilla Vim, but vanilla Vim somehow doesn't kill the job in a way that prints an error anyway... 

Can someone test that Gist with Neovim? If it works, it's probably a slightly better way since we'll have to duplicate that check in 3 other modules. Thanks!

**Comment by her** [comment]
@ludovicchabant I applied your patch and this fixes the `gutentags: ctags job failed, returned: 141` for me on `NVIM v0.4.2` 

Here's the applied changes: 

```
~/.vim/plugged/vim-gutentags $ git diff
diff --git a/autoload/gutentags.vim b/autoload/gutentags.vim
index e055f21..34f7eeb 100644
--- a/autoload/gutentags.vim
+++ b/autoload/gutentags.vim
@@ -701,5 +701,10 @@ function! gutentags#statusline_cb(fmt_cb, ...) abort
     return call(a:fmt_cb, [l:modules_in_progress])
 endfunction
 
+" Set a variable on exit so that we don't complain when a job gets killed.
+function! gutentags#on_vim_leave_pre() abort
+    let g:__gutentags_vim_is_leaving = 1
+endfunction
+
 " }}}
 
diff --git a/autoload/gutentags/ctags.vim b/autoload/gutentags/ctags.vim
index df56a8a..623f0f9 100644
--- a/autoload/gutentags/ctags.vim
+++ b/autoload/gutentags/ctags.vim
@@ -179,7 +179,7 @@ endfunction
 function! gutentags#ctags#on_job_exit(job, exit_val) abort
     call gutentags#remove_job_by_data('ctags', a:job)
 
-    if a:exit_val != 0
+    if a:exit_val != 0  && !g:__gutentags_vim_is_leaving
         call gutentags#warning("ctags job failed, returned: ".
                     \string(a:exit_val))
     endif
diff --git a/plugin/gutentags.vim b/plugin/gutentags.vim
index 8353849..41a9991 100644
--- a/plugin/gutentags.vim
+++ b/plugin/gutentags.vim
@@ -87,6 +87,8 @@ else
     let g:gutentags_script_ext = '.sh'
 endif
 
+let g:__gutentags_vim_is_leaving = 0
+
 " }}}
 
 " Gutentags Setup {{{
@@ -95,6 +97,7 @@ augroup gutentags_detect
     autocmd!
     autocmd BufNewFile,BufReadPost *  call gutentags#setup_gutentags()
     autocmd VimEnter               *  if expand('<amatch>')==''|call gutentags#setup_gutentags()|endif
+    autocmd VimLeavePre            *  call gutentags#on_vim_leave_pre()
 augroup end
 
 " }}}
```

NVIM version:

```
~/.vim/plugged/vim-gutentags $ vim --version
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/config -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-88369-176iaxs/neovim-0.4.2/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
~/.vim/plugged/vim-gutentags $ 
```

And showing that once the changes are `$ git stash` I can trigger the `gutentags: ctags job failed, returned: 141` again:

```
~/.vim/plugged/vim-gutentags $ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   autoload/gutentags.vim
	modified:   autoload/gutentags/ctags.vim
	modified:   plugin/gutentags.vim

no changes added to commit (use "git add" and/or "git commit -a")
~/.vim/plugged/vim-gutentags $ git stash
Saved working directory and index state WIP on master: eecb136 Fix incorrect documentation about default root markers.
~/.vim/plugged/vim-gutentags $ vim ~/work/web/app/models/user.rb 
gutentags: ctags job failed, returned: 141~/.vim/plugged/vim-gutentags $ 
```

**Pull request closed without merging**
