### PR TITLE
Add gtags-cscope module, based on ntnn/vim-gutentags:gtags-cscope

### PR DESCRIPTION
**Pull request by markwu**
Add `gtags-cscope` module, based on `ntnn/vim-gutentags:gtags-cscope` (https://github.com/ludovicchabant/vim-gutentags/pull/60 by @ntnn)
1. Add `set nocscopeverbose` / `set cscopeverbose`  to avoid duplicate databse errors, 
2. Add `g:gutentags_gtags_dbpath` to specify gtags db location, 
3. Add `g:gutentags_gtags_options_file` to specify additional user options, like `--gtagslabel`.

### CODE REVIEW

**Comment by ntnn** [comment]
@ludovicchabant Is there an update on this? It'd be quite nice to have this merged.
If you don't want to maintain it @markwu and/or myself could be noted as maintainers of that 'plugin' to vim-gutentags.

**Comment by ludovicchabant** [comment]
Oh yeah sorry, I totally let this slide. I still need to learn to properly setup and use `cscope` to test it... give me a few more days, otherwise I'll think about bringing in more maintainers.

**Comment by ludovicchabant** [comment]
Hey, I just want to update this PR and say I've been playing around with it. It's merged in my personal repo, and I added fixes to make it work on Windows, and with Vim8's native jobs (although I'm still fixing that last one... it's my first time using that API).

I'm not sure who the neovim support in this PR was supposed to work, it seems to me the `command_terminated` function is missing some hook up and will never get called.

I'm also trying to fix issues where you could be opening files from multiple projects inside the same Vim session, in which case the script breaks down because it doesn't handle adding multiple databases.... I'll keep you posted.

**Comment by ntnn** [comment]
@ludovicchabant  Thanks a bunch mate.

**Pull request merged**
